name: search-hashtags

on: 
   push:
   schedule:
      - cron: '*/30 * * * *'

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install dependencies
        run: python -m pip install --upgrade pip; pip install parler
      - name: execute py script
        env:
           jst: ${{ secrets.JST }}
           mst: ${{ secrets.MST }} 
        run: python search-hashtags.py
      - name: commit changes
         run |
            git config --global user.name 'Colin G. Wilson'
            git config --global user.email 'colingwilson7@gmail.com'
            git commit -am "Automated (see /.github/workflows/search-hashtags.yml)"
            git push
